name: documentatiion
run-name: Build and deply documentation
on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        #- uses: actions/setup-java@v3
        #  with:
        #    distribution: 'corretto'
        #    java-version: '8'
      - name: "Install plantuml"
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install plantuml -y
        shell: bash
      - name: 'Setup Python3'
        uses: actions/setup-python@v4
        with: 
          python-version: '^3.10.x'
      - name: Install Sphinx dependencies
        run: sudo pip install -r requirements.txt
        shell: bash
      - name: Build Sphinx Doc
        run: sphinx-build -b html ./source/ ./build/
        shell: bash
      - name: Compress HTML docs
        run: tar -czf ocs-docs.tar.gz ./build
      - name: Archive html docs
        uses: actions/upload-artifact@v3
        with:
          name: ocs-docs
          path: ${{ github.workspace }}/ocs-docs.tar.gz
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        
